### ISSUE TITLE
Gemma.cpp on the Android arm64-v8a

### ISSUE THREAD

**Issue by urim85** [google/gemma.cpp#62] opened 2024-02-28 05:43 UTC
I have made Gemma executable to run on Android arm64-v8a with below option.

> cmake -DCMAKE_TOOLCHAIN_FILE=/usr/lib/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake .

And it runs on my Android.
However there is error for reading weights.

> /# gemma --tokenizer tokenizer.spm --compressed_weights 2b-it-sfp.sbs --model 2b-it
> cache.path.c_str() : 2b-it-sfp.sbs
> 2b-it-sfp.sbs:3163184640
> BlobReader::Open open
> BlobReader::Open Read
> BlobReader::Open Allocate
> 3163184640, 0
> Cached compressed weights does not exist yet (code 155), compressing weights and creating file: 2b-it-sfp.sbs.

There is a failure in the "BlobReader::Open" function, on the line "blob_store_->CheckValidity(IO::FileSize(filename))".
The expected value of "IO::FileSize(filename)" is 3163184640, but it is currently returning 0.

However, before the line "hwy::CopySameSize(&bs, blob_store_.get())" in the "BlobReader::Open" function, the "IO::FileSize(filename)" is functioning correctly.

Anyway,
The comments in https://github.com/google/gemma.cpp/issues/21, it should work well.

Could you help me to figure out what I missed?

**Comment by jan-wassenberg** [comment] 2024-02-28 07:54
Hi, the error codes are simply line numbers, but it looks like your code is quite different.
On both main and dev, `if (file_size_ != file_size) return __LINE__;` should be line 218, not 155. Is the code modified?

I think the issue is that off_t on Android defaults to 32-bit. You can build with `-D_FILE_OFFSET_BITS=64` which fixes it for 15c and above. We'll also change to lseek64, thanks for pointing this out :)

**Comment by jan-wassenberg** [comment] 2024-02-29 01:38
I think this is fixed now, please reopen if not.

**Closed by jan-wassenberg** 2024-02-29 01:38 UTC
Labels: bug

**Comment by urim85** [comment] 2024-02-29 02:18
It works well!!

But sentencepiece with add_definitions(-D_FILE_OFFSET_BITS=64) has an error.

> /usr/lib/android-sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/fstream:968:9: error: use of undeclared identifier 'fseeko'
>     if (fseeko(__file_, __sp, SEEK_SET))

I put the definition like this

> FetchContent_Declare(sentencepiece GIT_REPOSITORY https://github.com/google/sentencepiece GIT_TAG 53de76561cfc149d3c01037f0595669ad32a5e7c)
> FetchContent_MakeAvailable(sentencepiece)
> 
> add_definitions(-D_FILE_OFFSET_BITS=64)
> 
> FetchContent_Declare(highway GIT_REPOSITORY https://github.com/google/highway.git GIT_TAG da250571a45826b21eebbddc1e50d0c1137dee5f)
> FetchContent_MakeAvailable(highway)

Thank you very much!

**Comment by jan-wassenberg** [comment] 2024-02-29 11:49
Please help us out by searching for such error messages on the web :)
This one is mentioned in https://developer.android.com/ndk/guides/common-problems, it seems we have to raise minSdkVersion to 24.
